//
//  SFSymbols.swift
//  Snjor
//
//  Created by Адам on 15.07.2024.
//

extension String {
  static let downloadCellButtonIcon = "arrow.down.circle.fill"
  static let backBarButtonIcon = "chevron.backward"
  static let globeEuropeAfricaFillIcon = "globe.europe.africa.fill"
  static let downloadBarButtonIcon = "arrow.down.app.fill"
  static let infoButtonIcon = "info.circle"
  static let cameraIcon = "camera.aperture"
  static let heartFillIcon = "heart.fill"
  static let suitHeartIcon = "suit.heart"
  static let noLikesIcon = "heart.slash"
  static let zero = "0"
  static let heartIcon = "heart"
  static let heartCircleIcon = "heart.circle"
  static let errorIcon = "exclamationmark.triangle"
  static let downloadsIcon = "tray.and.arrow.down.fill"
  static let toggleUpIcon = "arrow.up.backward.and.arrow.down.forward"
  static let toggleDownIcon = "arrow.down.forward.and.arrow.up.backward"
  static let cameraMacroIcon = "camera.macro"
  static let photoListItemIcon = "photo.on.rectangle"
  static let photoListSelectedItemIcon = "photo.fill.on.rectangle.fill"
  static let calendarIcon = "calendar"
  static let rightChevronIcon = "chevron.right"
  static let customPhotoIcon = "photos"
  static let photoAngledFillIcon = "photo.on.rectangle.fill"
  static let photoAngledIcon = "photo.on.rectangle"
  static let photoCircleIcon = "photo.circle"
  static let avatarBackgroundImage = "colors"
  static let checkmarkIcon = "checkmark.seal.fill"
  static let photoStackFillIcon = "photo.stack.fill"
  static let photoStackIcon = "photo.stack"
  static let macroIcon = "camera.macro"
  static let macroCircleIcon = "camera.macro.circle"
  static let xmarkCircleIcon = "xmark.circle.fill"
  static let locationIcon = "location"
  static let instIcon = "inst"
  static let twitIcon = "twit"
  static let photoCap = "photoCap"
  static let heartSlashIcon = "heart.slash"
  static let heartSlashFillIcon = "heart.slash.fill"
  static let photoSlashIcon = "rectangle.slash.fill"
  static let macroSlashIcon = "camera.macro.slash"
  static let wifiExclamationmarkIcon = "wifi.exclamationmark"
  static let exclamationmarkLockFillIcon = "exclamationmark.lock.fill"
  static let exclamationmarkIcloudIcon = "exclamationmark.icloud"
  static let ladybugFillIcon = "ladybug.fill"
}
